### ISSUE TITLE
Bold usernames in tg

### ISSUE THREAD

**Issue by nullawhale** [zhmylove/jxtg#1]
Add `parse_mode => 'HTML'` into `sendMessage` request and then place jabber username between `<b>` tag

**Comment by zhmylove** [comment]
This is a bad solution due too HTML injection threatment.
I'll check if Telegram client will highlight a text inside '*' symbols.

**Comment by zhmylove** [comment]
Well, it should be tested. I've found some problems with '<' symbol.

**Comment by nullawhale** [comment]
Except `HTML` there is a `Markdown` `parse_mode`. It's allows using `*` for bold text

**Comment by zhmylove** [comment]
Yep, I've read the api, but it's harder to prevent the injections.

**Comment by zhmylove** [comment]
Right now we should test current implemenation. I expect some problems with symbols conversion
```perl
   $text =~ s/</\&lt;/g;
   $text =~ s/>/\&gt;/g;
   $text =~ s/&/\&amp;/g;
```

**Comment by zhmylove** [comment]
Left AS-IS https://github.com/zhmylove/jxtg/commit/4e4cc418184ced7f98bfee9a8f560a55c998eaba
