### ISSUE TITLE
Send image url from tg to jabber

### ISSUE THREAD

**Issue by conformist-mw** [zhmylove/jxtg#11]
It would be cool to see images from telegram users in jabber chat, because sometimes we don't understand what is going on

**Comment by zhmylove** [comment]
Unfortunately Telegram does not provide URL-like API to images (may be due to storing them in a DB). I can download an image an upload it anywhere to get a permanent URL. Do you know any places where I can upload photos to without sms and registration? ^W without captcha and for free?

**Comment by zhmylove** [comment]
Fixed in https://github.com/zhmylove/jxtg/commit/ec7f633f8ce7a38550eba7feb44e4da9e41b3a66
